import { Trip, Parcel, Request, Delivery, ChatMessage, Conversation, User } from '@/types';

export const MOCK_USERS: User[] = [
  {
    id: 'user_1',
    name: 'Arjun Sharma',
    email: 'arjun@example.com',
    phone: '+91 98765 43210',
    rating: 4.8,
    totalDeliveries: 23,
    totalTrips: 15,
    joinedAt: '2024-01-15',
    verified: true,
    kycStatus: 'pending',
  },
  {
    id: 'user_2',
    name: 'Priya Singh',
    email: 'priya@example.com',
    phone: '+91 87654 32109',
    rating: 4.9,
    totalDeliveries: 41,
    totalTrips: 8,
    joinedAt: '2023-11-20',
    verified: true,
    kycStatus: 'pending',
  },
  {
    id: 'user_3',
    name: 'Rahul Kumar',
    email: 'rahul@example.com',
    phone: '+91 76543 21098',
    rating: 4.6,
    totalDeliveries: 12,
    totalTrips: 28,
    joinedAt: '2024-03-01',
    verified: false,
    kycStatus: 'pending',
  },
  {
    id: 'user_4',
    name: 'Sneha Patel',
    email: 'sneha@example.com',
    phone: '+91 65432 10987',
    rating: 4.7,
    totalDeliveries: 31,
    totalTrips: 19,
    joinedAt: '2023-09-10',
    verified: true,
    kycStatus: 'pending',
  },
];

export const MOCK_TRIPS: Trip[] = [
  {
    id: 'trip_1',
    userId: 'user_2',
    userName: 'Priya Singh',
    userRating: 4.9,
    fromCity: 'Mumbai',
    toCity: 'Delhi',
    date: '2026-04-25',
    time: '08:00 AM',
    vehicleType: 'flight',
    availableCapacity: 5,
    pricePerKg: 120,
    status: 'active',
    createdAt: '2026-04-22T06:00:00Z',
  },
  {
    id: 'trip_2',
    userId: 'user_3',
    userName: 'Rahul Kumar',
    userRating: 4.6,
    fromCity: 'Mumbai',
    toCity: 'Pune',
    date: '2026-04-23',
    time: '10:30 AM',
    vehicleType: 'car',
    availableCapacity: 10,
    pricePerKg: 40,
    status: 'active',
    createdAt: '2026-04-22T07:00:00Z',
  },
  {
    id: 'trip_3',
    userId: 'user_4',
    userName: 'Sneha Patel',
    userRating: 4.7,
    fromCity: 'Delhi',
    toCity: 'Jaipur',
    date: '2026-04-24',
    time: '02:00 PM',
    vehicleType: 'train',
    availableCapacity: 8,
    pricePerKg: 60,
    status: 'active',
    createdAt: '2026-04-22T08:00:00Z',
  },
];

export const MOCK_PARCELS: Parcel[] = [
  {
    id: 'parcel_1',
    userId: 'user_1',
    userName: 'Arjun Sharma',
    fromCity: 'Mumbai',
    toCity: 'Delhi',
    category: 'documents',
    description: 'Legal documents, urgent delivery needed',
    weight: 0.5,
    priceOffer: 200,
    status: 'open',
    createdAt: '2026-04-22T09:00:00Z',
  },
  {
    id: 'parcel_2',
    userId: 'user_3',
    userName: 'Rahul Kumar',
    fromCity: 'Mumbai',
    toCity: 'Pune',
    category: 'electronics',
    description: 'Laptop charger and accessories',
    weight: 1.2,
    priceOffer: 80,
    status: 'matched',
    createdAt: '2026-04-21T14:00:00Z',
  },
];

export const MOCK_REQUESTS: Request[] = [
  {
    id: 'req_1',
    parcelId: 'parcel_2',
    tripId: 'trip_2',
    senderId: 'user_3',
    senderName: 'Rahul Kumar',
    travellerId: 'current_user',
    travellerName: 'You',
    status: 'pending',
    price: 80,
    message: 'I can carry this on my way to Pune tomorrow.',
    createdAt: '2026-04-22T10:00:00Z',
    updatedAt: '2026-04-22T10:00:00Z',
  },
];

export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    id: 'conv_1',
    requestId: 'req_1',
    participants: ['current_user', 'user_3'],
    participantNames: { 'current_user': 'You', 'user_3': 'Rahul Kumar' },
    parcelDescription: 'Laptop charger and accessories',
    route: 'Mumbai → Pune',
    lastMessage: {
      id: 'msg_3',
      conversationId: 'conv_1',
      senderId: 'user_3',
      senderName: 'Rahul Kumar',
      text: 'Can we meet at the station at 10am?',
      timestamp: '2026-04-22T10:30:00Z',
      read: false,
    },
  },
];

export const MOCK_MESSAGES: { [convId: string]: ChatMessage[] } = {
  conv_1: [
    {
      id: 'msg_1',
      conversationId: 'conv_1',
      senderId: 'current_user',
      senderName: 'You',
      text: 'Hi! I can carry your parcel to Pune.',
      timestamp: '2026-04-22T10:00:00Z',
      read: true,
    },
    {
      id: 'msg_2',
      conversationId: 'conv_1',
      senderId: 'user_3',
      senderName: 'Rahul Kumar',
      text: 'Great! What time are you leaving?',
      timestamp: '2026-04-22T10:15:00Z',
      read: true,
    },
    {
      id: 'msg_3',
      conversationId: 'conv_1',
      senderId: 'user_3',
      senderName: 'Rahul Kumar',
      text: 'Can we meet at the station at 10am?',
      timestamp: '2026-04-22T10:30:00Z',
      read: false,
    },
  ],
};

export const CURRENT_USER: User = {
  id: 'current_user',
  name: 'Demo User',
  email: 'demo@example.com',
  phone: '+91 99999 00000',
  rating: 4.5,
  totalDeliveries: 7,
  totalTrips: 4,
  joinedAt: '2026-01-01',
  verified: true,
  kycStatus: 'pending',
};

export const CITIES = [
  'Mumbai', 'Delhi', 'Bangalore', 'Hyderabad', 'Chennai',
  'Pune', 'Kolkata', 'Jaipur', 'Ahmedabad', 'Surat',
  'Lucknow', 'Bhopal', 'Indore', 'Nagpur', 'Patna',
];
